// <auto-generated />
using System;
using GymUmbraco.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GymUmbraco.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260518092545_SeedExercises")]
    partial class SeedExercises
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GymUmbraco.Models.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExerciseName = "Bänkpress"
                        },
                        new
                        {
                            Id = 2,
                            ExerciseName = "Lutande hantelpress"
                        },
                        new
                        {
                            Id = 3,
                            ExerciseName = "Kabel-flyes"
                        },
                        new
                        {
                            Id = 4,
                            ExerciseName = "Dips"
                        },
                        new
                        {
                            Id = 5,
                            ExerciseName = "Pullups"
                        },
                        new
                        {
                            Id = 6,
                            ExerciseName = "Pullups smalt grepp"
                        },
                        new
                        {
                            Id = 7,
                            ExerciseName = "Latsdrag"
                        },
                        new
                        {
                            Id = 8,
                            ExerciseName = "Skivstångsrodd"
                        },
                        new
                        {
                            Id = 9,
                            ExerciseName = "Hantelrodd"
                        },
                        new
                        {
                            Id = 10,
                            ExerciseName = "Sittande kabelrodd"
                        },
                        new
                        {
                            Id = 11,
                            ExerciseName = "Shrugs"
                        },
                        new
                        {
                            Id = 12,
                            ExerciseName = "Militärpress"
                        },
                        new
                        {
                            Id = 13,
                            ExerciseName = "Sittande hantelpress"
                        },
                        new
                        {
                            Id = 14,
                            ExerciseName = "Sidolyft"
                        },
                        new
                        {
                            Id = 15,
                            ExerciseName = "Bakre axlar maskin"
                        },
                        new
                        {
                            Id = 16,
                            ExerciseName = "Face Pulls"
                        },
                        new
                        {
                            Id = 17,
                            ExerciseName = "Knäböj"
                        },
                        new
                        {
                            Id = 18,
                            ExerciseName = "Marklyft"
                        },
                        new
                        {
                            Id = 19,
                            ExerciseName = "Benpress"
                        },
                        new
                        {
                            Id = 20,
                            ExerciseName = "Benspark"
                        },
                        new
                        {
                            Id = 21,
                            ExerciseName = "Lårcurl"
                        },
                        new
                        {
                            Id = 22,
                            ExerciseName = "Vadpress"
                        },
                        new
                        {
                            Id = 23,
                            ExerciseName = "Bulgariska utfall"
                        },
                        new
                        {
                            Id = 24,
                            ExerciseName = "Bicepscurl"
                        },
                        new
                        {
                            Id = 25,
                            ExerciseName = "Hammercurl"
                        },
                        new
                        {
                            Id = 26,
                            ExerciseName = "Triceps pushdown"
                        },
                        new
                        {
                            Id = 27,
                            ExerciseName = "Tricepspress med hantel"
                        });
                });

            modelBuilder.Entity("GymUmbraco.Models.GymProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ProgramName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("GymPrograms");
                });

            modelBuilder.Entity("GymUmbraco.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firstname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePicUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GymUmbraco.Models.Workout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GymProgramId")
                        .HasColumnType("int");

                    b.Property<string>("WorkoutName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GymProgramId");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("GymUmbraco.Models.WorkoutExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<int>("Rep")
                        .HasColumnType("int");

                    b.Property<int>("Set")
                        .HasColumnType("int");

                    b.Property<int>("WorkoutId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutId");

                    b.ToTable("WorkoutExercises");
                });

            modelBuilder.Entity("GymUmbraco.Models.GymProgram", b =>
                {
                    b.HasOne("GymUmbraco.Models.User", "User")
                        .WithMany("Programs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GymUmbraco.Models.Workout", b =>
                {
                    b.HasOne("GymUmbraco.Models.GymProgram", "GymProgram")
                        .WithMany("Workouts")
                        .HasForeignKey("GymProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GymProgram");
                });

            modelBuilder.Entity("GymUmbraco.Models.WorkoutExercise", b =>
                {
                    b.HasOne("GymUmbraco.Models.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymUmbraco.Models.Workout", "Workout")
                        .WithMany("WorkoutExercises")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("GymUmbraco.Models.GymProgram", b =>
                {
                    b.Navigation("Workouts");
                });

            modelBuilder.Entity("GymUmbraco.Models.User", b =>
                {
                    b.Navigation("Programs");
                });

            modelBuilder.Entity("GymUmbraco.Models.Workout", b =>
                {
                    b.Navigation("WorkoutExercises");
                });
#pragma warning restore 612, 618
        }
    }
}
